name: Build and Publish to PyPI

on:
    workflow_call:
        inputs:
            publish_target:
                description: 'The target for publishing: "test" or "prod"'
                required: true
                type: string

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:

    - name: Set the publish target credentials as environment variables.
      id: set-publish-target-credentials
      run: |
        echo "TWINE_USERNAME=${{ secrets.NAPE_EVAL_PYPI_USERNAME }}" >> $GITHUB_ENV
        if [ "${{ inputs.publish_target }}" == "test" ]; then
          echo "Using test publish credentials"
          echo "TWINE_PASSWORD=${{ secrets.NAPE_EVAL_PYPI_TEST_PASSWORD }}" >> $GITHUB_ENV
          echo "PYPI_URL=https://test.pypi.org/legacy" >> $GITHUB_ENV
        elif [ "${{ inputs.publish_target }}" == "prod" ]; then
          echo "Using production publish credentials"
          echo "TWINE_PASSWORD=${{ secrets.NAPE_EVAL_PYPI_PASSWORD }}" >> $GITHUB_ENV
          echo "PYPI_URL=https://upload.pypi.org/legacy/" >> $GITHUB_ENV
        else
          echo "Error: Invalid publish_target '${{ inputs.publish_target }}' provided. It must be either 'test' or 'prod'."
          exit 1
        fi

    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Python dependencies & build tools
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel twine build

    - name: Build nape-evaluator
      run: make build-release

    - name: Publish nape-evaluator
      run: make pypi-publish