name: Build and Publish to PyPI

on:
    workflow_call:
        inputs:
            pypi_url:
                description: 'The repository URL for PyPI or Test PyPI'
                required: true
                type: string

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: release
    
    env:
      PYPI_URL: ${{ inputs.pypi_url }}


    steps:

    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Build
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel twine build

    - name: Build and Publish
      run: make build-release

    - name: Publish package to PYPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: ${{ inputs.pypi_url }}
        packages-dir: build-output/