name: Build and Publish to PyPI

on:
    workflow_call:
        inputs:
            pypi_url:
                description: 'The repository URL for PyPI or Test PyPI'
                required: true
                type: string

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: release
    
    env:
      PYPI_URL: ${{ inputs.pypi_url }}


    steps:
    - name: Debug - Check PYPI_URL
      run: |
            echo "PYPI_URL is set to: $PYPI_URL"

#    - name: Checkout the code
#      uses: actions/checkout@v3
#
#    - name: Set up Python
#      uses: actions/setup-python@v4
#      with:
#        python-version: '3.x'
#
#    - name: Install build dependencies
#      run: |
#        python -m pip install --upgrade pip
#        python -m pip install setuptools wheel twine build
#
#    - name: Build and Publish
#      run: make pypi-publish