name: Rust Standard - Multi-Architecture Compile Workflow

on:
    workflow_call:
        inputs:
            rust-project:
                description: 'The Rust project that is being built and pushed.'
                required: true
                type: string
            binary-repo-name:
                description: 'The name to store this as in the binary repo.'
                required: true
                type: string
            version:
                description: 'The version to store this as in the binary repo.'
                required: true
                type: string
        outputs:
            artifacts_paths:
                description: 'A list of paths to the built artifacts.'
                value: ${{ jobs.build.outputs.artifacts_paths }}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # Ensure that jobs keep processing if one fails
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            arch: x86_64
#          - os: ubuntu-latest
#            target: aarch64-unknown-linux-gnu
#            arch: aarch64
#          - os: ubuntu-latest
#            target: x86_64-unknown-linux-musl
#            arch: x86_64
#          - os: ubuntu-latest
#            target: aarch64-unknown-linux-musl
#            arch: aarch64
          - os: macos-12
            target: x86_64-apple-darwin
            arch: x86_64
          - os: macos-latest
            target: aarch64-apple-darwin
            arch: aarch64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            arch: x86_64

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Install Dependencies for Cross-Compilation (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          # Combo 1: x86_64 to aarch64-unknown-linux-gnu
          if [ "${{ matrix.target }}" == "aarch64-unknown-linux-gnu" ]; then
            sudo apt-get install -y gcc-aarch64-linux-gnu pkg-config libssl-dev

          # Combo 2: x86_64 to x86_64-unknown-linux-musl
          elif [ "${{ matrix.target }}" == "x86_64-unknown-linux-musl" ]; then
            sudo apt-get install -y musl-tools pkg-config libssl-dev

          # Combo 3: x86_64 to aarch64-unknown-linux-musl
          elif [ "${{ matrix.target }}" == "aarch64-unknown-linux-musl" ]; then
            sudo apt-get install -y gcc-aarch64-linux-gnu musl-tools pkg-config libssl-dev
          fi

          sudo apt-get update

      - name: Set up OpenSSL and pkg-config for Cross-Compilation
        if: runner.os == 'Linux' && matrix.target != 'x86_64-unknown-linux-gnu'
        run: |

          if [ "${{ matrix.target }}" == "aarch64-unknown-linux-gnu" ]; then
            export OPENSSL_DIR=/usr/aarch64-linux-gnu
            export PKG_CONFIG_PATH=/usr/aarch64-linux-gnu/lib/pkgconfig

          elif [ "${{ matrix.target }}" == "x86_64-unknown-linux-musl" ]; then
            export OPENSSL_DIR=/usr/local/musl
            export PKG_CONFIG_PATH=/usr/local/musl/lib/pkgconfig

          elif [ "${{ matrix.target }}" == "aarch64-unknown-linux-musl" ]; then
            export OPENSSL_DIR=/usr/aarch64-linux-musl
            export PKG_CONFIG_PATH=/usr/aarch64-linux-musl/lib/pkgconfig
          fi

      - name: Build Release
        run: make ma-release-build PROJECT=${{ inputs.rust-project }} OS_ARCH_TARGET=${{ matrix.target }}
        
      - name: Upload Binary
        uses: actions/upload-artifact@v3
        with:
          name: nape-cli-${{ inputs.version }}-${{ matrix.target }}
          path: |
            target/${{ matrix.target }}/release/*
                                                 
      - name: Set Output Artifact Path
        id: set_artifacts
        run: echo "::set-output name=artifacts::${{ matrix.target }}-${{ inputs.version }}"

    outputs:
      artifacts_paths: ${{ steps.set_artifacts.outputs.artifacts }}
                                                           